### ISSUE TITLE
Upgrade to regex 0.2

### ISSUE THREAD

**Issue by P-E-Meunier** [chronotope/parse-zoneinfo#1]
This is a minor comment, I'm trying to optimise my dependencies on a large project, and parse-zoneinfo depends on an old version of the regex crate, which itself depends on several older crates.

It would be great if parse-zoneinfo were upgraded to regex 0.2.

**Comment by P-E-Meunier** [comment]
Hi! Great to see it's fixed, any chance we can have this version on crates.io? I keep recompiling several versions of regex (and all dependencies).

**Comment by quodlibetor** [comment]
As far as I know @djzin is the only person who can upload a new version of this crate to crates.io.

**Comment by djzin** [comment]
ah ok let me publish this now

**Comment by quodlibetor** [comment]
Thanks @djzin! I believe that the latest commit is completely correct. Also there is a [chronotope release manager](https://github.com/orgs/chronotope/teams/release-manager/members) team which contains only @lifthrasiir , if you feel comfortable adding him as someone who can do the release [using `cargo --add`](http://doc.crates.io/crates-io.html#cargo-owner) like so:

```
 cargo owner --add github:chronotope:release-manager
```

This would increase the bus factor. Based on the docs I linked to, since that is a team, you would still be the only "real" owner and therefore the only person who can add/remove further people.
